azure:
  keyvault:
    uri: https://key-jack-valut.vault.azure.net/                # The URI to the Azure Key Vault used
    tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47          # The Tenant ID for your Azure Key Vault (needed if you are not using managed identity).
    client-id: 56cd62ad-5fcf-45f3-a210-2e3f5c384d0d         # The Client ID that has been setup with access to your Azure Key Vault (needed if you are not using managed identity).
    client-secret: F.e2s80H9v-J-81c6_kr1hH90ZLgAoK_Tm      # The Client Secret that will be used for accessing your Azure Key Vault (needed if you are not using managed identity).
    # managed-identity:  # The user-assigned managed identity client-id to use.
    # If the above 4 properties are empty, then system-assigned managed identity will be used.
server:
  port: 8443
  ssl:
    key-alias: jackCerr0624 # The alias corresponding to the certificate in Azure Key Vault.
    key-store-type: AzureKeyVault  # The keystore type that enables the use of Azure Key Vault for your server-side SSL certificate.
    # client-auth: need  # Used for MTLS
    # trust-store-type: AzureKeyVault  # Used for MTLS